<?xml version="1.0"?>
<!-- Jonathan Burkhard, ETH Zurich, Switzerland
   01.05.2019 
   -->

<robot name="cube1" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- Incudes -->
  <!-- <xacro:include filename="$(find reflex_description)/urdf/reflex_takktile_2.xacro" />   -->
  <!-- <xacro:include filename="$(find reflex_description)/urdf/reflex.transmission.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/reflex.gazebo.xacro" />
  <xacro:include filename="$(find reflex_description)/materials/reflex.materials.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/tactile_sensors.xacro" />
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.xacro"/>
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.urdf.xacro"/> -->

<!-- Properties -->
  <xacro:property name="rectangle_x"     value="0.08"/>
  <xacro:property name="rectangle_y" value="0.08"/>
  <xacro:property name="rectangle_z"   value="0.08"/>
  <xacro:property name="mass"   value="2.5"/>

  <!-- ${flex_length/2.0} -->


<!-- ******************************************************************************************************* -->
<!-- Objects to drop -->
<!-- ******************************************************************************************************* -->

  <!-- <link name="square">
    <inertial>
      <origin xyz="0.0 0.0 0.0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001"  iyz="0.0"
                                           izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.20 0.08"/>
      </geometry>
      <material
        name="base_color">
        <xacro:base_color/>
      </material>
    </visual>
    <collision>
       <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <max_vel>0</max_vel>
            <min_depth>0.003</min_depth>
            <maxVel>0</maxVel> 
          </ode>
        </contact>
      </surface>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
    </collision>
  </link> -->


        <!-- <pose>0.4 -0.2 0.775 0 0 0</pose> -->
        <!-- <model name="cube1"> -->
      <link name="link">
        <!-- <pose>0 0 0.025 0 0 0</pose> -->
        <inertial>
          <mass>0.0565</mass>
          <inertia>
            <ixx>2.3541666666666672e-05</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>2.3541666666666672e-05</iyy>
            <iyz>0</iyz>
            <izz>2.3541666666666672e-05</izz>
          </inertia>
        </inertial>
        <collision name="collision">
          <geometry>
            <box>
              <size>0.05 0.05 0.05</size>
            </box>
          </geometry>
          <surface>
            <contact>
              <poissons_ratio>0.347</poissons_ratio>
              <elastic_modulus>8.8e+09</elastic_modulus>
              <ode>
                <kp>100000</kp>
                <kd>1</kd>
                <max_vel>1.0</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
            <friction>
              <torsional>
                <coefficient>1.0</coefficient>
                <use_patch_radius>0</use_patch_radius>
                <surface_radius>0.05</surface_radius>
              </torsional>
            </friction>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <box>
              <size>0.05 0.05 0.05</size>
            </box>
          </geometry>
          <!-- <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Wood</name>
            </script>
          </material> -->
        </visual>
  </link>
  <!-- </model> -->
  <!-- <gazebo>  
    <mu1>1.0</mu1>  
    <mu2>1.0</mu2>  
    <minDepth>0.003</minDepth>  
    <maxVel>0</maxVel>  
  </gazebo> -->



</robot>