<?xml version="1.0"?>
<!-- Jonathan Burkhard, ETH Zurich, Switzerland
   01.05.2019 
   
   TODO:  - Clean the code
          - Create the macro of simplifying creation of the repetitive part
   -->

<robot name="object_to_catch" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- Incudes -->
  <!-- <xacro:include filename="$(find reflex_description)/urdf/reflex_takktile_2.xacro" />   -->
  <!-- <xacro:include filename="$(find reflex_description)/urdf/reflex.transmission.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/reflex.gazebo.xacro" />
  <xacro:include filename="$(find reflex_description)/materials/reflex.materials.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/tactile_sensors.xacro" />
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.xacro"/>
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.urdf.xacro"/> -->

<!-- Properties -->
  <xacro:property name="rectangle_x"     value="0.08"/>
  <xacro:property name="rectangle_y" value="0.08"/>
  <xacro:property name="rectangle_z"   value="0.08"/>
  <xacro:property name="mass"   value="20.5"/>

  <!-- ${flex_length/2.0} -->


<!-- ******************************************************************************************************* -->
<!-- Objects to drop -->
<!-- ******************************************************************************************************* -->

  <link name="square">
    <inertial>
      <origin xyz="0.0 0.0 0.0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001"  iyz="0.0"
                                           izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.20 0.08"/>
      </geometry>
      <material
        name="base_color">
        <xacro:base_color/>
      </material>
    </visual>
    <collision>
       <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <!-- Change max_vel and/or min_depth to keep cones from "bouncing" -->
        <contact>
          <ode>
            <!--max_vel>0</max_vel-->
            <min_depth>0.003</min_depth>
            <maxVel>0</maxVel> 
          </ode>
        </contact>
      </surface>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.08 0.08"/>
      </geometry>
    </collision>
  </link>

  <!-- <gazebo>  
    <mu1>1.0</mu1>  
    <mu2>1.0</mu2>  
    <minDepth>0.003</minDepth>  
    <maxVel>0</maxVel>  
  </gazebo> -->



</robot>