<?xml version="1.0"?>
<!-- Jonathan Burkhard, ETH Zurich, Switzerland
   01.05.2019 
   
   TODO:  - Clean the code
          - Create the macro of simplifying creation of the repetitive part
   -->

<robot name="reflex_takktile_2" 
  xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Incudes -->
  <!-- <xacro:include filename="$(find reflex_description)/urdf/reflex_takktile_2.xacro" />   -->
  <xacro:include filename="$(find reflex_description)/urdf/reflex.transmission.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/reflex.gazebo.xacro" />
  <xacro:include filename="$(find reflex_description)/materials/reflex.materials.xacro" />
  <xacro:include filename="$(find reflex_description)/urdf/tactile_sensors.xacro" />
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.xacro"/>
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.urdf.xacro"/>

  <!-- Properties -->
  <xacro:property name="flex_link_mass" value="0.01"/>
  <xacro:property name="proximal_link_mass" value="0.01"/>
  <xacro:property name="distal_link_mass" value="0.01"/>
  <xacro:property name="proximal_pad_mass" value="0.01"/>
  <xacro:property name="distal_pad_mass" value="0.01"/>
  <xacro:property name="swivel_link_mass" value="0.01"/>
  <xacro:property name="base_link_mass" value="0.34"/><!-- 0.74 -->
  <xacro:property name="pad_mass" value="0.1"/>

  <!-- Parameters Limits Joints -->
  <!-- Preshape -->
  <xacro:property name="preshape_joint_limit_effort" value="0.50"/>
  <xacro:property name="preshape_joint_limit_velocity" value="0.5"/>
  <xacro:property name="preshape_joint_limit_lower" value="-0.00"/>
  <xacro:property name="preshape_joint_limit_upper" value="1.65"/>

  <!-- Proximal -->
  <xacro:property name="proximal_joint_limit_effort" value="0.50"/>
  <xacro:property name="proximal_joint_limit_velocity" value="0.5"/>
  <xacro:property name="proximal_joint_limit_lower" value="0.0"/>
  <xacro:property name="proximal_joint_limit_upper" value="2.09440"/>

  <!-- Distal -->
  <xacro:property name="distal_joint_limit_effort" value="0.50"/>
  <xacro:property name="distal_joint_limit_velocity" value="0.5"/>
  <xacro:property name="distal_joint_limit_lower" value="0.0"/>
  <xacro:property name="distal_joint_limit_upper" value="1.7"/>

  <!-- ################ ################ ################ ################ ################ ################ -->
  <!-- ################ XACRO PORTION OF THE URDF, FOR MAKING THE FLEXIBLE JOINTS ################ -->
  <!-- ################ ################ ################ ################ ################ ################ -->

  <xacro:property name="flex_length" value="0.016" />
  <xacro:property name="distal_length" value="0.050" />
  <xacro:property name="num_steps" value="9" />
  <xacro:property name="prox_length" value="0.060" />
  <xacro:property name="pi" value="3.1415" />

  <!-- ################ ################ ################ ################ ################ ################ -->
  <!-- ################ THE SECTION CREATED BY SOLIDWORKS EXPORTER, CUT AND PASTE THIS IN HERE ################ -->
  <!-- ################ YOU CAN ALTER THE COLORS FROM HERE ################ -->
  <!-- ################ COMMENT OUT ALL dist*_joint PIECES OF THIS URDF SO THE FLEX JOINTS CAN LINK UP ################ -->
  <!-- ################ ################ ################ ################ ################ ################ -->

  <link name="base_link">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="${base_link_mass}"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <!-- TODO: Change the BASE OF the hand to the version 2 -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="$(find reflex_description)/meshes/base_link.stl" /> -->
         <mesh filename="package://reflex_description/meshes/base_link.stl" />
         <!-- <mesh filename="package://iiwa_description/meshes/iiwa7/visual/link_0.stl"/> -->
      </geometry>
      <!-- <material name="base_color">
        <xacro:base_color/>
      </material> -->
    </visual>
    <!-- TODO: Change the BASE OF the hand to the version 2 -->
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/base_link.stl" />
      </geometry>
    </collision>
  </link>

  <!-- For a tool on a arm, uncomment this part -->
  <joint name="tool_joint" type="fixed">
    <parent link="iiwa_link_ee" />
    <child link = "base_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0 0.0 3.14159" />
  </joint>

  <link name="pad">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/pad.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/pad.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="pad_joint" type="fixed">
    <origin xyz="0.02 0 0.063" rpy="1.5707963267949 5.55111512312578E-17 -1.5707963267949" />
    <parent link="base_link" />
    <child link="pad" />
    <axis xyz="0 0 0" />
  </joint>

  <!-- Add the tool tips which is the pose of the hand effector -->
  <!-- TODO Check the offset of the tool! -->
  <joint name="tool_ee_joint" type="fixed">
    <parent link="base_link" />
    <child link = "tool_link_ee" />
    <origin xyz="0 0 0.1275" rpy="0 ${0.0/1.0} 0" />
  </joint>

  <!--  The TCP frame is here defined -->
  <link name="tool_link_ee">
    <!-- <inertial>
    <origin xyz="0.0 0.0 0.0"/>
    <mass value="0.0001"/>
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
  </inertial>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${length}" radius="${radius}"/>
    </geometry>
    <material name="">
      <xacro:pad_color/>
    </material>
  </visual>

  <collision>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    <geometry>
      <cylinder length="${length}" radius="${radius}"/>
    </geometry>
  </collision> -->
  </link>


  <!-- *****************************************FINGER 1**************************************************** -->

  <link name="swivel_1">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/swivel_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:swivel_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/swivel_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="preshape_1" type="revolute">
    <origin xyz="0.0503973683071414 -0.026 0.063" rpy="6.75550818663469E-16 1.97993848419069E-16 -2.77555756156289E-16" />
    <parent link="base_link" />
    <child link="swivel_1" />
    <axis xyz="0 0 -1" />
    <!-- <limit effort="30" velocity="1.0" lower="-0.0872665" upper="2.0944" /> -->
    <limit effort="${preshape_joint_limit_effort}" velocity="${preshape_joint_limit_velocity}" lower="${preshape_joint_limit_lower}" upper="${preshape_joint_limit_upper}" />
  </joint>

  <link name="proximal_1">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0"/>
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:proximal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="proximal_joint_1" type="revolute">
    <origin xyz="0.01 0 0.0186" rpy="-6.20039667432211E-16 0.05 2.22044604925031E-16" />
    <parent link="swivel_1" />
    <child link="proximal_1" />
    <axis xyz="0 -1 0" />
    <limit effort="${proximal_joint_limit_effort}" velocity="${proximal_joint_limit_velocity}" lower="${proximal_joint_limit_lower}" upper="${proximal_joint_limit_upper}" />
  </joint>

  <link name="proximal_pad_1">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <!-- Keep for souvenir -->
    <!-- <collision name="proximal_pad_1_collision">
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
    </collision> -->
    <collision>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="prox1_pad_joint" type="fixed">
    <origin xyz="0 0 0" rpy="1.5707963267949 0 -1.5707963267949" />
    <parent link="proximal_1" />
    <child link="proximal_pad_1" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="flex_link_1">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <!-- <origin xyz="${flex_length/2.0} -0.008 0.001" rpy="${pi/2} 0 ${pi/2}" /> -->
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
      <!-- <material name="">
          <xacro:flex_color/>
        </material> -->
    </visual>

    <collision>
      <!-- <origin xyz="${flex_length/2.0} -0.008 0.001" rpy="${pi/2} 0 ${pi/2}" /> -->
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
    </collision>
  </link>

  <!-- TODO: DISTANCE TO CHECK!!!! -->
  <joint name="flex_joint_1" type="fixed">
    <parent link="proximal_1"/>
    <child link="flex_link_1"/>
    <!-- <origin xyz="0.060 0 0.003"/>
    <axis xyz="0 -1 0"/> -->
    <origin xyz="${prox_length} 0 ${0.001}" />
    <axis xyz="0 -1 0"/>
  </joint>

  <link name="distal_1">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <!-- <origin xyz="-0.077 0.007 0.007" rpy="3.1459 0 0" /> -->
      <origin xyz="-0.077 0.007 0.007" rpy="3.1459 0 0" />
      <!-- <origin xyz="0.0 0.0 0.0" rpy="3.1459 0 0" /> -->
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:distal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.077 0.007 0.007" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="distal_joint_1" type="revolute">
    <origin xyz="${flex_length-0.01} 0 0.001" rpy="0 0 0" />
    <parent link="flex_link_1" />
    <child link="distal_1" />
    <axis xyz="0 -1 0" />
    <limit effort="${distal_joint_limit_effort}" velocity="${distal_joint_limit_velocity}" lower="${distal_joint_limit_lower}" upper="${distal_joint_limit_upper}" />
  </joint>

  <link name="distal_pad_1">
    <inertial>

      <origin xyz="0.0 0.0 0.0"/>

      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <collision>
      <!-- <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <min_depth>0.003</min_depth>
            <maxVel>0</maxVel> 
          </ode>
        </contact>
      </surface> -->
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="dist1_pad_joint" type="fixed">
    <origin xyz="-0.01 0 0.001" rpy="1.5707963267949 0 -1.5707963267949" />
    <parent link="distal_1" />
    <child link="distal_pad_1" />
    <axis xyz="0 0 0" />
  </joint>

  <!-- *****************************************FINGER 2**************************************************** -->

  <link name="swivel_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/swivel_2.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:swivel_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/swivel_2.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="preshape_2" type="revolute">
    <origin xyz="0.0503973683071413 0.0259999999999999 0.063" rpy="1.22459340959228E-15 -7.33448407631817E-16 -1.66533453693773E-16" />
    <parent link="base_link" />
    <child link="swivel_2" />
    <axis xyz="0 0 -1" />
    <!-- <limit effort="30" velocity="1.0" lower="-0.0872665" upper="2.0944" /> -->
    <limit effort="${preshape_joint_limit_effort}" velocity="${preshape_joint_limit_velocity}" lower="${-preshape_joint_limit_upper}" upper="${-preshape_joint_limit_lower}" />
  </joint>

  <link name="proximal_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0"/>
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:proximal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0"/>
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="proximal_joint_2" type="revolute">
    <origin xyz="0.01 0 0.0186" rpy="-1.16908225836102E-15 0.05 1.11022302462515E-16" />
    <parent link="swivel_2" />
    <child link="proximal_2" />
    <axis xyz="0 -1 0" />
    <limit effort="${proximal_joint_limit_effort}" velocity="${proximal_joint_limit_velocity}" lower="${proximal_joint_limit_lower}" upper="${proximal_joint_limit_upper}" />
  </joint>

  <link name="proximal_pad_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="prox2_pad_joint" type="fixed">
    <origin xyz="0 0 0" rpy="1.5707963267949 0 -1.5707963267949" />
    <parent link="proximal_2" />
    <child link="proximal_pad_2" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="flex_link_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
      <!-- <material name="">
          <xacro:flex_color/>
        </material> -->
    </visual>

    <collision>
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
    </collision>
  </link>

  <!-- TODO: DISTANCE TO CHECK!!!! -->
  <joint name="flex_joint_2" type="fixed">
    <parent link="proximal_2"/>
    <child link="flex_link_2"/>
    <!-- <origin xyz="0.060 0 0.003"/>
    <axis xyz="0 -1 0"/> -->
    <origin xyz="${prox_length} 0 ${0.001}" />
    <axis xyz="0 -1 0"/>
  </joint>

  <link name="distal_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.077 0.007 0.006" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:distal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.077 0.007 0.006" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
        <!-- <box size="${flex_length*1.0} 0.014 0.006"/> -->
      </geometry>
    </collision>
  </link>

  <joint name="distal_joint_2" type="revolute">
    <origin xyz="${flex_length-0.01} 0 0.001" rpy="0 0 0" />
    <parent link="flex_link_2" />
    <child link="distal_2" />
    <axis xyz="0 -1 0" />
    <limit effort="${distal_joint_limit_effort}" velocity="${distal_joint_limit_velocity}" lower="${distal_joint_limit_lower}" upper="${distal_joint_limit_upper}" />
  </joint>

  <link name="distal_pad_2">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <collision>
      <!-- <surface>
        <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <min_depth>0.003</min_depth>
            <maxVel>0</maxVel> 
          </ode>
        </contact>
      </surface> -->
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="dist2_pad_joint" type="fixed">
    <origin xyz="-0.01 0 0.001" rpy="1.5707963267949 0 -1.5707963267949" />
    <parent link="distal_2" />
    <child link="distal_pad_2" />
    <axis xyz="0 0 0" />
  </joint>

  <!-- *****************************************FINGER 3**************************************************** -->

  <link name="proximal_3">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0"/>
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:proximal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.011 0.007 0.011" rpy="3.1459 0 0"/>
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="proximal_joint_3" type="revolute">
    <origin xyz="-0.0299999999999996 0 0.0816000000000002" rpy="-5.55111512312578E-17 0.05 3.14159265358979" />
    <parent link="base_link" />
    <child link="proximal_3" />
    <axis xyz="0 -1 0" />
    <limit effort="${proximal_joint_limit_effort}" velocity="${proximal_joint_limit_velocity}" lower="${proximal_joint_limit_lower}" upper="${proximal_joint_limit_upper}" />
  </joint>

  <link name="proximal_pad_3">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="prox3_pad_joint" type="fixed">
    <origin xyz="0 0 0" rpy="1.5707963267949 1.22460635382238E-16 -1.5707963267949" />
    <parent link="proximal_3" />
    <child link="proximal_pad_3" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="flex_link_3">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
      <!-- <material name="">
          <xacro:flex_color/>
        </material> -->
    </visual>

    <collision>
      <origin xyz="${flex_length/2.0} 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <!-- <mesh filename="package://reflex_description/meshes/flex_block.stl" /> -->
        <box size="${flex_length*1.0} 0.014 0.006"/>
      </geometry>
    </collision>
  </link>

  <!-- TODO: DISTANCE TO CHECK!!!! -->
  <joint name="flex_joint_3" type="fixed">
    <parent link="proximal_3"/>
    <child link="flex_link_3"/>
    <!-- <origin xyz="0.060 0 0.003"/>
    <axis xyz="0 -1 0"/> -->
    <origin xyz="${prox_length} 0 ${0.001}" />
    <axis xyz="0 -1 0"/>
  </joint>

  <link name="distal_3">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.077 0.007 0.006" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:distal_color/>
      </material> -->
    </visual>

    <collision>
      <origin xyz="-0.077 0.007 0.006" rpy="3.1459 0 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="distal_joint_3" type="revolute">
    <origin xyz="${flex_length-0.01} 0 0.001" rpy="0 0 0" />
    <parent link="flex_link_3" />
    <child link="distal_3" />
    <axis xyz="0 -1 0" />
    <limit effort="${distal_joint_limit_effort}" velocity="${distal_joint_limit_velocity}" lower="${distal_joint_limit_lower}" upper="${distal_joint_limit_upper}" />
  </joint>

  <link name="distal_pad_3">
    <inertial>
      <!-- TODO: CALCULATES CENTER OF MASS -->
      <origin xyz="0.0 0.0 0.0"/>
      <!-- TODO: CALCULATES THE MASS AND INERTIAs -->
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>

    <visual>
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
      <!-- <material name="">
        <xacro:pad_color/>
      </material> -->
    </visual>

    <collision>
      <!-- <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <min_depth>0.003</min_depth>
            <maxVel>0</maxVel> 
          </ode>
        </contact>
      </surface> -->
      <origin xyz="-0.00825 0.009 0.057" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/distal_pad_1.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="dist3_pad_joint" type="fixed">
    <origin xyz="-0.01 0 0.001" rpy="1.5707963267949 0 -1.5707963267949" />
    <parent link="distal_3" />
    <child link="distal_pad_3" />
    <axis xyz="0 0 0" />
  </joint>

  <!-- ******************************************************************************************************* -->
  <!-- Objects to drop -->
  <!-- ******************************************************************************************************* -->

  <!-- <link name="square">
    <inertial>
      <origin xyz="0.0 0.0 0.0"/>
      <mass value="0.5"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="base_color">
        <xacro:base_color/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
  </link> -->

  <!-- ################ ################ ################ ################ ################ ################ -->
  <!-- ################ THIS SECTION LINKS THE MARKERS (TACTILE DATA) TO THE CAD MESH ################ -->
  <!-- ################ COPY AND PASTE THIS FROM urdf/homemade_marker_portion_urdf  ################ -->
  <!-- ################ ################ ################ ################ ################ ################ -->

  <!-- <joint name="base_tactile_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_tactile" />
  </joint>

  <link name="base_tactile"/>

  <link name="proximal_1_tactile" />

  <joint name="proximal_1_tactile_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="proximal_1" />
    <child link="proximal_1_tactile" />
  </joint>

  <joint name="proximal_2_tactile_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="proximal_2" />
    <child link="proximal_2_tactile" />
  </joint>

  <link name="proximal_2_tactile"/>

  <joint name="proximal_3_tactile_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="proximal_3" />
    <child link="proximal_3_tactile" />
  </joint>

  <link name="proximal_3_tactile"/>

  <joint name="distal_1_tactile_joint" type="fixed">
    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
    <parent link="distal_1" />
    <child link="distal_1_tactile" />
  </joint>

  <link name="distal_1_tactile"/>

  <joint name="distal_2_tactile_joint" type="fixed">
    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
    <parent link="distal_2" />
    <child link="distal_2_tactile" />
  </joint>

  <link name="distal_2_tactile"/>

  <joint name="distal_3_tactile_joint" type="fixed">
    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
    <parent link="distal_3" />
    <child link="distal_3_tactile" />
  </joint>

  <link name="distal_3_tactile"/> -->

  <!-- Tactile sensors -->
  <!-- Example -->
  <!-- <collision name="proximal_pad_1_collision">
      <origin xyz="-0.008 0.014 -0.002" rpy="1.5708 1.5708 0" />
      <geometry>
        <mesh filename="package://reflex_description/meshes/proximal_pad_1.stl" />
      </geometry>
    </collision> -->

  <!-- <link name="proximal_1_sensor_1"> 
    <inertial>
      <mass value="0.00001"/>
      <inertia ixx="0.00000000001" ixy="0.0" ixz="0.0" iyy="0.00000000001" iyz="0.0" izz="0.00000000001"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0.0 0" />
      <geometry>
        
        <cylinder length="0.002" radius="0.004"/>
      </geometry>
      
    </visual>

    <collision>
      <origin xyz="0 0 0.0" rpy="0 0.0 0" />
      <geometry>
       
        <cylinder length="0.002" radius="0.004"/>
      </geometry>
    </collision>
  </link> -->



</robot>