reflex_takktile_2:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------

  preshape_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: preshape_1
    pid: {p: 0.5, i: 0.0, d: 0.0}
