reflex_takktile_2:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Proximal Position Controllers ---------------------------------------

  preshape_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: preshape_1
    pid: {p: 2.5, i: 0.05, d: 0.05}

  preshape_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: preshape_2
    pid: {p: 2.5, i: 0.05, d: 0.05}

  proximal_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_1
    pid: {p: 2.5, i: 0.05, d: 0.05}

  proximal_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_2
    pid: {p: 2.5, i: 0.05, d: 0.05}

  proximal_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_3
    pid: {p: 2.5, i: 0.05, d: 0.05}


  # Distal Position Controllers ---------------------------------------

  distal_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: distal_joint_1
    pid: {p: 2.5, i: 0.05, d: 0.05}

  distal_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: distal_joint_2
    pid: {p: 2.5, i: 0.05, d: 0.05}

  distal_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: distal_joint_3
    pid: {p: 2.5, i: 0.05, d: 0.05}
