reflex_takktile_2:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------

  preshape_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: preshape_1
    pid: {p: 2.5, i: 0.0, d: 0.0}

  preshape_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: preshape_2
    pid: {p: 2.5, i: 1.0, d: 1.0}

  proximal_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_1
    pid: {p: 2.5, i: 0.0, d: 0.0}

  proximal_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_2
    pid: {p: 2.5, i: 0.0, d: 0.0}

  proximal_joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: proximal_joint_3
    pid: {p: 2.5, i: 1.0, d: 1.0}
